const displayed_types = ['Protein', 'Total lipid (fat)', 'Carbohydrate, by difference', 
'Sugars, total including NLEA', 'Fiber, total dietary', 'Cholesterol', 'Fatty acids, total saturated', 'Fatty acids, total monounsaturated', 'Fatty acids, total polyunsaturated',
'Vitamin A, RAE', 'Vitamin E (alpha-tocopherol)', 'Vitamin D (D2 + D3)', 'Vitamin C, total ascorbic acid', 'Vitamin B-6', 'Vitamin B-12']

const recommended_daily = {
    'Protein': { amount: 56, unit: 'G' },
    'Total lipid (fat)': { amount: 55.5 , unit: 'G' },
    'Carbohydrate, by difference': { amount: 130, unit: 'G' },
    'Energy': { amount: 2250, unit: 'KCAL' },
    // 'Alcohol, ethyl': { amount: null, unit: 'G' },
    // 'Water': { amount: 3000, unit: 'G' },
    'Caffeine': { amount: 400, unit: '<MG' },
    // 'Theobromine': { amount: 263, unit: 'MG' },
    'Sugars, total including NLEA': { amount: 100, unit: 'G' },
    'Fiber, total dietary': { amount: 30, unit: 'G' },
    'Calcium, Ca': { amount: 1000, unit: 'MG' },
    'Iron, Fe': { amount: 12, unit: 'MG' },
    'Magnesium, Mg': { amount: 360, unit: 'MG' },
    'Phosphorus, P': { amount: 700, unit: 'MG' },
    'Potassium, K': { amount: 4700, unit: 'MG' },
    'Sodium, Na': { amount: 2300, unit: 'MG' },
    'Zinc, Zn': { amount: 9.5, unit: 'MG' },
    'Copper, Cu': { amount: 0.9, unit: 'MG' },
    'Selenium, Se': { amount: 55, unit: 'UG' },
    'Retinol': { amount: 900, unit: 'UG' },
    'Vitamin A, RAE': { amount: 800, unit: 'UG' },
    // 'Carotene, beta': { amount: , unit: 'UG' },
    // 'Carotene, alpha': { amount: 322, unit: 'UG' },
    'Vitamin E (alpha-tocopherol)': { amount: 15, unit: 'MG' },
    'Vitamin D (D2 + D3)': { amount: 18, unit: 'UG' },
    // 'Cryptoxanthin, beta': { amount: 334, unit: 'UG' },
    // 'Lycopene': { amount: 337, unit: 'UG' },
    // 'Lutein + zeaxanthin': { amount: 338, unit: 'UG' },
    'Vitamin C, total ascorbic acid': { amount: 82.5, unit: 'MG' },
    'Thiamin': { amount: 1.15, unit: 'MG' },
    'Riboflavin': { amount: 1.2, unit: 'MG' },
    'Niacin': { amount: 15, unit: 'MG' },
    'Vitamin B-6': { amount: 1.5, unit: 'MG' },
    'Folate, total': { amount: 500, unit: 'UG' },
    'Vitamin B-12': { amount: 418, unit: 'UG' },
    'Choline, total': { amount: 485, unit: 'MG' },
    'Vitamin K (phylloquinone)': { amount: 105, unit: 'UG' },
    // 'Folic acid': { amount: 431, unit: 'UG' },
    // 'Folate, food': { amount: 432, unit: 'UG' },
    // 'Folate, DFE': { amount: 435, unit: 'UG' },
    // 'Vitamin E, added': { amount: 573, unit: 'MG' },
    // 'Vitamin B-12, added': { amount: 578, unit: 'UG' },
    'Cholesterol': { amount: 300, unit: '<MG' },
    'Fatty acids, total saturated': { amount: 14, unit: '<G' },
    // 'SFA 4:0': { amount: 607, unit: 'G' },
    // 'SFA 6:0': { amount: 608, unit: 'G' },
    // 'SFA 8:0': { amount: 609, unit: 'G' },
    // 'SFA 10:0': { amount: 610, unit: 'G' },
    // 'SFA 12:0': { amount: 611, unit: 'G' },
    // 'SFA 14:0': { amount: 612, unit: 'G' },
    // 'SFA 16:0': { amount: 613, unit: 'G' },
    // 'SFA 18:0': { amount: 614, unit: 'G' },
    // 'MUFA 18:1': { amount: 617, unit: 'G' },
    // 'PUFA 18:2': { amount: 618, unit: 'G' },
    // 'PUFA 18:3': { amount: 619, unit: 'G' },
    // 'PUFA 20:4': { amount: 620, unit: 'G' },
    // 'PUFA 22:6 n-3 (DHA)': { amount: 621, unit: 'G' },
    // 'MUFA 16:1': { amount: 626, unit: 'G' },
    // 'PUFA 18:4': { amount: 627, unit: 'G' },
    // 'MUFA 20:1': { amount: 628, unit: 'G' },
    // 'PUFA 20:5 n-3 (EPA)': { amount: 629, unit: 'G' },
    // 'MUFA 22:1': { amount: 630, unit: 'G' },
    // 'PUFA 22:5 n-3 (DPA)': { amount: 631, unit: 'G' },
    'Fatty acids, total monounsaturated': { amount: 22, unit: 'G' },
    'Fatty acids, total polyunsaturated': { amount: 15, unit: 'G' }
  }